import {RawHtml} from "./components/raw-html.tsx";
import {If} from "./components/if.tsx";
import {Else} from "./components/else.tsx";
import {type ElementType} from "react";
import {For} from "./components/for.tsx";
import {
    Text,
    A,
    Abbr,
    Address,
    Area,
    Article,
    Aside,
    Audio,
    B,
    Base,
    Bdi,
    Bdo,
    Blockquote,
    Body,
    Br,
    Button,
    Canvas,
    Caption,
    Cite,
    Code,
    Col,
    Colgroup,
    Data,
    Datalist,
    Dd,
    Del,
    Details,
    Dfn,
    Dialog,
    Div,
    Dl,
    Dt,
    Em,
    Embed,
    Fieldset,
    Figcaption,
    Figure,
    Footer,
    Form,
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    Head,
    Header,
    Hgroup,
    Hr,
    Html,
    I,
    Iframe,
    Img,
    Input,
    Ins,
    Kbd,
    Label,
    Legend,
    Li,
    Link,
    Main,
    Map,
    Mark,
    Menu,
    Meta,
    Meter,
    Nav,
    Noscript,
    Ol,
    Optgroup,
    Option,
    Output,
    P,
    Picture,
    Pre,
    Progress,
    Q,
    Rp,
    Rt,
    Ruby,
    S,
    Samp,
    Script,
    Search,
    Section,
    Select, Slot, Small, Source, Span, Strong, Style, Sub, Summary
} from "./components/html-elements.tsx";

const FLOW_CONTROL_COMPONENTS: Record<string, ElementType> = {
    if: If,
    else: Else,
    for: For,
}

const HTML_COMPONENTS: Record<string, ElementType> = {
    "raw-html": RawHtml,
    text: Text,
    a: A,
    abbr: Abbr,
    address: Address,
    area: Area,
    article: Article,
    aside: Aside,
    audio: Audio,
    b: B,
    base: Base,
    bdi: Bdi,
    bdo: Bdo,
    blockquote: Blockquote,
    body: Body,
    br: Br,
    button: Button,
    canvas: Canvas,
    caption: Caption,
    cite: Cite,
    code: Code,
    col: Col,
    colgroup: Colgroup,
    data: Data,
    datalist: Datalist,
    dd: Dd,
    del: Del,
    details: Details,
    dfn: Dfn,
    dialog: Dialog,
    div: Div,
    dl: Dl,
    dt: Dt,
    em: Em,
    embed: Embed,
    fieldset: Fieldset,
    figcaption: Figcaption,
    figure: Figure,
    footer: Footer,
    form: Form,
    h1: H1,
    h2: H2,
    h3: H3,
    h4: H4,
    h5: H5,
    h6: H6,
    head: Head,
    header: Header,
    hgroup: Hgroup,
    hr: Hr,
    html: Html,
    i: I,
    iframe: Iframe,
    img: Img,
    input: Input,
    ins: Ins,
    kbd: Kbd,
    label: Label,
    legend: Legend,
    li: Li,
    link: Link,
    main: Main,
    map: Map,
    mark: Mark,
    menu: Menu,
    meta: Meta,
    meter: Meter,
    nav: Nav,
    noscript: Noscript,
    object: Object,
    ol: Ol,
    optgroup: Optgroup,
    option: Option,
    output: Output,
    p: P,
    picture: Picture,
    pre: Pre,
    progress: Progress,
    q: Q,
    rp: Rp,
    rt: Rt,
    ruby: Ruby,
    s: S,
    samp: Samp,
    script: Script,
    search: Search,
    section: Section,
    select: Select,
    slot: Slot,
    small: Small,
    source: Source,
    span: Span,
    strong: Strong,
    style: Style,
    sub: Sub,
    summary: Summary
}

const DEFAULT_COMPONENTS: Record<string, ElementType> = {
    ...HTML_COMPONENTS,
    ...FLOW_CONTROL_COMPONENTS
}

export {DEFAULT_COMPONENTS}
